export const projects = [
  {
    title: "Pizza Hut Brasil - App",
    description: "Lorem Ipsum",
    mainTechs: [
      "React Native",
      "Typescript",
      "Jest",
      "Redux",
      "i18next",
      "Styled Components",
      "Firebase",
      "Google Maps SDK",
      "Axios",
      "Socket.io",
      "Formik",
    ],
    mainImage: "",
    year: 2023,
    projectInfo: <></>,
  },
  {
    title: "Pizza Hut Brasil - Web",
    description: "Lorem Ipsum",
    mainTechs: [
      "React",
      "Typescript",
      "Jest",
      "Vite",
      "Redux",
      "i18next",
      "Styled Components",
      "Framer Motion",
      "Google Maps SDK",
      "Axios",
      "Socket.io",
      "React Hook Form",
    ],
    mainImage: "",
    year: 2023,
    projectInfo: <></>,
  },
  {
    title: "My Portfolio",
    description: "Lorem Ipsum",
    mainTechs: ["Next", "React", "Typescript", "Tailwind"],
    mainImage: "",
    year: 2023,
    projectInfo: <></>,
  },
  {
    title: "Crie Seus Posts",
    description: "Lorem Ipsum",
    mainTechs: [
      "React",
      "Typescript",
      "Apollo GraphQL",
      "Single-spa",
      "Konva.js",
      "Styled Components",
    ],
    mainImage: "",
    year: 2022,
    projectInfo: <></>,
  },
  {
    title: "Predikta - Dashboard(Thermal Manipulation)",
    description: "Lorem Ipsum",
    mainTechs: [
      "React",
      "Javascript",
      "Axios",
      "Konva.js",
      "Styled Components",
      "AWS Amplify",
    ],
    mainImage: "",
    year: 2022,
    projectInfo: <></>,
  },
  {
    title: "Predikta Pass",
    description: "Lorem Ipsum",
    mainTechs: [
      "React Native",
      "Javascript",
      "Expo",
      "Axios",
      "Styled Components",
      "AWS Amplify",
      "Google Maps SDK",
    ],
    mainImage: "",
    year: 2021,
    projectInfo: <></>,
  },
  {
    title: "QR Loc - Dashboard",
    description: "Lorem Ipsum",
    mainTechs: [
      "React",
      "Javascript",
      "Axios",
      "Styled Components",
      "Google Maps SDK",
    ],
    mainImage: "",
    year: 2021,
    projectInfo: <></>,
  },
  {
    title: "QR Loc - App",
    description: "Lorem Ipsum",
    mainTechs: ["React Native", "Javascript", "Axios", "Styled Components"],
    mainImage: "",
    year: 2021,
    projectInfo: <></>,
  },
  {
    title: "Planus",
    description: "Lorem Ipsum",
    mainTechs: ["React", "Javascript", "Axios", "Styled Components"],
    mainImage: "",
    year: 2020,
    projectInfo: <></>,
  },
  {
    title: "Betim Sem Dengue",
    description: "Lorem Ipsum",
    mainTechs: ["React Native", "Javascript"],
    mainImage: "",
    year: 2019,
    projectInfo: <></>,
  },
];
